### PR TITLE
Merge pull request #6 from GoralTomaszGorski/authorization-function

### PR DESCRIPTION
**Pull request by GoralTomaszGorski**
Authorization-function

### CODE REVIEW

**Comment by gorskimarcin96** [comment]
@GoralTomaszGorski Do you need help with resolve conflicts?

**Comment by GoralTomaszGorski** [comment]
Yes I need :)

**Comment by gorskimarcin96** [comment]
Look a diagram. You created branch `authentication-function` from `origin/authorization-function` and now you have conflicts, because both branches have different changes in same lines. You should create new branch from `main`.

image

**Comment by gorskimarcin96** [comment]
i did `git merge`
image
next i selected branch `main`
image
and finally i closed correct code with new roles.


https://www.awesomescreenshot.com/video/24328391?key=e7863cc42799d97c3b6c482f07e0b8ba

**Comment by GoralTomaszGorski** [comment]
Thank you for your help and useful material, now git will be easy for me;)

**Pull request merged**
